feat: Add window drag area
marc2332/freya pull request #597
Opened 2024-04-30 08:40 UTC by ZeroX-DG

Closes https://github.com/marc2332/freya/issues/262

2024-04-30 08:42 UTC, marc2332 requested changes
Just like I had it in my mind, I will try it asap. Just left a tiny comment

2024-04-30 08:42 UTC, marc2332 commented on crates/components/src/window_drag_area.rs
> +    let onmousedown = move |_| platform.drag_window();
```suggestion
    let onmousedown = move |e: MouseEvent| {
        e.stop_propagation();
        platform.drag_window();
    };
```

2024-04-30 12:37 UTC, marc2332 requested changes

2024-04-30 12:37 UTC, marc2332 commented on examples/window_drag_area.rs
> +    )
```suggestion
    rsx!(
        rect {
            width: "100%",
            height: "100%",
            WindowDragArea {
                rect {
                    width: "100%",
                    height: "50%",
                    background: "rgb(28, 28, 28)",
                    color: "white",
                    main_align: "center",
                    label {
                        width: "100%",
                        text_align: "center",
                        "Drag Me!"
                    }
                }
            }
            rect {
                width: "100%",
                height: "50%",
                main_align: "center",
                label {
                    text_align: "center",
                    "Use the top half to drag the window"
                }
            }
        }
    )
```

2024-04-30 12:38 UTC, marc2332 commented
Just a comment to clean up the example, it works perfectly!

2024-05-01 15:50 UTC, marc2332 approved these changes

2024-05-01 22:15 UTC, marc2332 commented
Just saw https://github.com/ZeroX-DG/raven ! You are crazy haha 🚀 

Let me know if you have any issue/doubt/missing feature and I will be happy to help 😄

2024-05-02 19:33 UTC, merged

2024-05-02 23:56 UTC, ZeroX-DG commented
Haha thanks! You're doing a great job fixing my feature requests lightning fast haha.