Use Metal on macOS
marc2332/freya pull request #789
Opened 2024-07-14 14:13 UTC by reyamir

2024-08-20 06:49 UTC, marc2332 requested changes

2024-08-20 06:49 UTC, marc2332 commented on crates/renderer/src/skia/metal_surface.rs
Where is the surface? 🤔

2024-08-20 06:49 UTC, marc2332 commented on crates/renderer/src/skia/gl_surface.rs
> +pub struct SkiaSurface {
I would probably rename this to something like GlSurface and then have a type alias be stored in the window state instead, same thing for the metal surface `MetalSurface`

2024-08-20 06:49 UTC, marc2332 commented on crates/renderer/src/skia/metal_surface.rs
> +    pub(crate) scale_factor: f64,
I don't think scale_factor should stored in the surface

2024-08-21 00:05 UTC, reyamir commented
I will rework on this on this weekend, as well as add vulkan support too.

2024-08-25 10:22 UTC, marc2332 commented
hey @reyamir ! I just opened https://github.com/marc2332/freya/pull/822 which should make adding metal easier :)

2024-08-26 00:11 UTC, reyamir commented
> hey @reyamir ! I just opened #822 which should make adding metal and other drivers easier :)

that great, I will rewrite my PR

2024-09-03 07:46 UTC, closed without merging