enhancement: add support for `color` in `svg`
marc2332/freya pull request #797
Opened 2024-07-16 05:31 UTC by Aiving

Closes #796

2024-07-16 06:39 UTC, marc2332 requested changes
Why not `fill` instead of `color`? The former is used for text

2024-07-16 06:43 UTC, Aiving commented
> Why not `fill` instead of `color`? The former is used for text

I thought that adding a new property to `StyleState`, `AttributeName`/`Type` etc. would be a bit overkill, but if there is no problem with that I can implement it right now

2024-07-16 06:51 UTC, Aiving commented
@marc2332 done!

2024-07-21 15:48 UTC, geom3trik commented on crates/core/src/elements/svg.rs
>                  canvas.restore();
You've got to restore here but no corresponding save because it's been removed

2024-08-03 07:26 UTC, marc2332 requested changes
Can you also add an example?

2024-08-03 07:26 UTC, marc2332 commented on crates/elements/src/definitions.rs
> +        #[doc = include_str!("_docs/attributes/color.md")]
You will need to create the doc file as well
```suggestion
        #[doc = include_str!("_docs/attributes/fill.md")]
```

2024-08-04 07:42 UTC, marc2332 commented
Does this implementation really make sense?

For example, given this code:

```rs
<svg width="525" height="190" viewBox="0 0 525 190" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="250" height="190" fill="#D9D9D9"/>
    <rect x="275.5" y="0.5" width="249" height="189" stroke="black"/>
</svg>
```

Both `rect` will have their colors (`fill="#D9D9D9"` and `stroke="black"`) overrode when using this new `fill` attribute

Do you think that makes sense?

2024-08-04 07:42 UTC, marc2332 requested changes
btw

2024-08-04 07:42 UTC, marc2332 commented on crates/elements/src/_docs/attributes/fill.md
> +    let svg_content = include_str!("./ferris.svg");
```suggestion
    let svg_content = include_str!("../../../examples/settings.svg");
```

2024-08-05 07:45 UTC, Aiving commented
> Does this implementation really make sense?
> 
> For example, given this code:
> 
> ```rust
> <svg width="525" height="190" viewBox="0 0 525 190" fill="none" xmlns="http://www.w3.org/2000/svg">
>     <rect width="250" height="190" fill="#D9D9D9"/>
>     <rect x="275.5" y="0.5" width="249" height="189" stroke="black"/>
> </svg>
> ```
> 
> Both `rect` will have their colors (`fill="#D9D9D9"` and `stroke="black"`) overrode when using this new `fill` attribute
> 
> Do you think that makes sense?

Honestly, I don't think so. Based on the Skia source code, there is a function [`resolveSvgColor`](https://github.com/google/skia/blob/938b8b8efdface485b737512805582445015fb14/modules/svg/src/SkSVGRenderContext.cpp#L471) where some ``fPresentationContext`` is used, where you can set the color used for `currentColor`. However, it is in `SkSVGRenderContext` which I can't find in `skia-safe`. In case I do, I will try to make a PR in `skia-safe` that adds the `SkSVGRenderContext`.

2024-11-23 15:28 UTC, marc2332 requested changes

2024-11-23 15:28 UTC, marc2332 commented on crates/state/src/style.rs
> +    pub fill_stroke: (Option<Color>, Option<Color>),
Why is it a tuple? better to just put each color in its own field right? Don't see the need for a tuple
```suggestion
    pub svg_fill: Option<Color>,
    pub svg_stroke: Option<Color>,
```

2024-11-23 15:28 UTC, marc2332 commented on crates/state/src/style.rs
> +                    self.fill_stroke.0 = Some(Color::parse(value)?);
```suggestion
                    self.svg_stroke = Some(Color::parse(value)?);
```

2024-11-23 15:28 UTC, marc2332 commented on crates/state/src/style.rs
> +                    self.fill_stroke.1 = Some(Color::parse(value)?);
```suggestion
                    self.svg_fill = Some(Color::parse(value)?);
```

2024-11-23 15:28 UTC, marc2332 commented on crates/state/src/style.rs
> +            AttributeName::Fill,
You are missing Stroke right?

```suggestion
            AttributeName::Fill,
            AttributeName::Stroke,
```

2024-11-23 15:28 UTC, marc2332 commented on crates/core/src/elements/svg.rs
> +                if let Some(color) = node_style.fill_stroke.0.as_ref() {
```suggestion
                if let Some(color) = node_style.svg_stroke.as_ref() {
```

2024-11-23 15:28 UTC, marc2332 commented on crates/core/src/elements/svg.rs
> +                if let Some(color) = node_style.fill_stroke.1.as_ref() {
```suggestion
                if let Some(color) = node_style.svg_fill.as_ref() {
```

2024-11-23 15:49 UTC, Aiving commented
@marc2332 done!

2024-11-24 10:52 UTC, merged