feat: per-side border widths
marc2332/freya pull request #836
Opened 2024-08-31 23:28 UTC by Tropix126

Adds support for adding border-widths per side. Made based on observation of figma's stroke rendering system.

## Basic Rundown

Rather than using Skia's stroking API, we instead draw the border as a second rect with either a larger or smaller radius (the offset for roundness is calculated by `RectElement::border_corner_radius_offset`). We then mask out a smaller rect from the inside of the border rect.

What this gives us is the ability to offset the border rect allowing for different widths on each side.

## Current Limitations (this is a draft PR)
- The parser requires the user to input exactly four width values and no less currently. This means all examples and devtools are currently broken. I need to find a way to parse the widths in a clean way.
- Devtools are broken as mentioned before.
- Zero-width borders bleed through from under the rect if they happen to render on a subpixel. This will be fixed once pixel snapping is implemented.

## Some cursed showcases

Superellipse roundness with variable widths on each side. (this rendering is actually more correct than figma's, which doesn't do squircle calculations on borders :D)
![image](https://github.com/user-attachments/assets/7ea1b912-84e5-4306-84ce-44ee5a4af300)

Variable widths with variable corner radius.
![image](https://github.com/user-attachments/assets/e061bde9-ef64-44f8-ba38-618e60977f65)

2024-09-14 06:02 UTC, Tropix126 commented
Linux build is failing for reasons I can't determine. The build also took 49 minutes :p

2024-09-14 09:28 UTC, marc2332 commented
> Linux build is failing for reasons I can't determine. The build also took 49 minutes :p

Check the skia bindings

2024-09-15 10:31 UTC, marc2332 requested changes
Would be nice to have the border.rs example update showing this new thing right?

2024-09-15 10:36 UTC, marc2332 requested changes
this branch:
![image](https://github.com/user-attachments/assets/23752bf4-22c0-4906-b2b5-b6764454eb0b)

main:
![image](https://github.com/user-attachments/assets/39c1a542-d2f3-486c-b25f-9b45ef7ecdb1)

🤔

2024-09-19 16:40 UTC, Tropix126 commented
Rendering quality has been fixed. Example has been updated as part of #889 (which is dependent on this PR).

2024-09-28 13:40 UTC, marc2332 requested changes

2024-09-28 13:40 UTC, marc2332 commented on crates/state/src/values/border.rs
> +            && self.style != BorderStyle::None
```suggestion
        (self.width.top != 0.0
            || self.width.left != 0.0
            || self.width.bottom != 0.0
            || self.width.right != 0.0)
            && self.fill != Fill::Color(Color::TRANSPARENT)
            && self.style != BorderStyle::None
```

2024-09-28 16:14 UTC, marc2332 requested changes

2024-09-28 16:14 UTC, marc2332 commented on examples/border.rs
Could you update this example to contain a multi side widths border?

2024-09-28 16:14 UTC, marc2332 commented on examples/border.rs
rest lgtm, will merge after this

2024-09-28 16:16 UTC, marc2332 approved these changes

2024-09-28 16:16 UTC, merged