feat: add attributes for most AccessKit properties
marc2332/freya pull request #882
Opened 2024-09-14 04:28 UTC by Tropix126

- Renames `a11y_focus` and `a11y_auto_focus` to `focus` and `auto_focus` for now (not final).
- Adds the following attributes: `a11y_name`, `a11y_description`, `a11y_value`, `a11y_access_key`, `a11y_author_id`, `a11y_keyboard_shortcut`, `a11y_language`, `a11y_placeholder`, `a11y_role_description`, `a11y_state_description`, `a11y_tooltip`, `a11y_url`, `a11y_row_index_text`, `a11y_column_index_text`, `a11y_scroll_x`, `a11y_scroll_x_min`, `a11y_scroll_x_max`, `a11y_scroll_y`, `a11y_scroll_y_min`, `a11y_scroll_y_max`, `a11y_numeric_value`, `a11y_min_numeric_value`, `a11y_max_numeric_value`, `a11y_numeric_value_step`, `a11y_numeric_value_jump`, `a11y_row_count`, `a11y_column_count`, `a11y_row_index`, `a11y_column_index`, `a11y_row_span`, `a11y_column_span`, `a11y_level`, `a11y_size_of_set`, `a11y_position_in_set`, `a11y_color_value`, `a11y_expanded`, `a11y_selected`, `a11y_hovered`, `a11y_hidden`, `a11y_linked`, `a11y_multiselectable`, `a11y_required`, `a11y_visited`, `a11y_busy`, `a11y_live_atomic`, `a11y_modal`, `a11y_touch_transparent`, `a11y_read_only`, `a11y_disabled`, `a11y_is_spelling_error`, `a11y_is_grammar_error`, `a11y_is_search_match`, `a11y_is_suggestion`, `a11y_role`, `a11y_invalid`, `a11y_toggled`, `a11y_live`, `a11y_default_action_verb`, `a11y_orientation`, `a11y_sort_direction`, `a11y_current`, `a11y_auto_complete`, `a11y_has_popup`, `a11y_list_style`, `a11y_vertical_offset`.
- `NodeBuilder` is now constructed in freya's `state` crate rather than `AccessibilityManager`. This is done, because `accesskit::Node` has a more memory efficient representation of this, making it an ideal way to store a lot of properties/flags.
- Currently node associations (e.g. `a11y_named_by`) and actions/custom actions are unimplemented. These will need further consideration (actions need their own events and parser, associations need some sort of ID system) and are out of scope of this PR.

2024-09-14 07:58 UTC, marc2332 commented
> Renames a11y_id and a11y_auto_focus to focus and auto_focus for now (not final, but given the volume of accesskit properties I'm just trying to distinguish focus-related stuff from accesskit stuff).
I don't want this

2024-09-15 21:18 UTC, Tropix126 commented
> > Renames a11y_id and a11y_auto_focus to focus and auto_focus for now (not final, but given the volume of accesskit properties I'm just trying to distinguish focus-related stuff from accesskit stuff).
> 
> I don't want this

Have reverted the changes in that regard. Since #884 works in a similar area to this PR, i've rebased it off of that.

2024-09-29 11:11 UTC, marc2332 requested changes

2024-09-29 11:11 UTC, marc2332 commented on crates/state/src/accessibility.rs
> +                    TagName::Rect => Some(NodeBuilder::new(Role::GenericContainer)),
`rect`s should not be accesible by default, not fully sure about the rest

2024-10-05 17:24 UTC, marc2332 approved these changes

2024-10-06 08:05 UTC, merged