fix: absolute positioning doesn't ignore the padding of the parent element
marc2332/freya pull request #986
Opened 2024-10-16 15:36 UTC by Aiving

2024-11-01 16:01 UTC, marc2332 requested changes
What about the root node when measuring it in torin.rs?

2024-11-01 16:22 UTC, Aiving commented
> What about the root node when measuring it in torin.rs?

I'm not sure I understand correctly what the question is about. Do you mean absolute positioning of the root element itself or something else?

2024-11-01 16:26 UTC, marc2332 commented
> > What about the root node when measuring it in torin.rs?
> 
> I'm not sure I understand correctly what the question is about. Do you mean absolute positioning of the root element itself or something else?

Torin starts measuring from the root node by calling `measure_node`, you changed how this method is called when measuring descendants but not when is called upon the root node of the measurement.

By root node I don't specifically refer to the root node of the app but to the root node from where the measuring starts, which could be different is the measure is incremental.

2024-11-01 16:27 UTC, marc2332 commented
Perhaps this your way is not a good approach, if the 3 places where this function is called require some special logic maybe its better to move it inside or create a simple function to abstract it

2024-12-24 11:06 UTC, marc2332 commented
I don't agree with this, if an element is absolute I still think it should consider the parent's padding. I recently added the `global` position too, maybe that fits your use case better?

2025-06-21 13:46 UTC, marc2332 commented
closing to inactivity, feel free to open it again in the future again

2025-06-21 13:46 UTC, closed without merging